// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZIsQzV26AJzVh9evjvYgey40CTtUi89w',
    appId: '1:561338680433:web:71bbfe5130bc78a43f07d0',
    messagingSenderId: '561338680433',
    projectId: 'mail-ceb33',
    authDomain: 'mail-ceb33.firebaseapp.com',
    storageBucket: 'mail-ceb33.appspot.com',
    measurementId: 'G-S9DCXY542D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6TFodsrnsb3MDx2u-xYmahWgKS5UfASs',
    appId: '1:561338680433:android:57e70a03094cc5623f07d0',
    messagingSenderId: '561338680433',
    projectId: 'mail-ceb33',
    storageBucket: 'mail-ceb33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZJ-M4-Y0MThYWv--PViWGENIPUO-Yz2M',
    appId: '1:561338680433:ios:ff40de0828fd2c7e3f07d0',
    messagingSenderId: '561338680433',
    projectId: 'mail-ceb33',
    storageBucket: 'mail-ceb33.appspot.com',
    iosBundleId: 'com.example.mailLogs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZJ-M4-Y0MThYWv--PViWGENIPUO-Yz2M',
    appId: '1:561338680433:ios:ff40de0828fd2c7e3f07d0',
    messagingSenderId: '561338680433',
    projectId: 'mail-ceb33',
    storageBucket: 'mail-ceb33.appspot.com',
    iosBundleId: 'com.example.mailLogs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZIsQzV26AJzVh9evjvYgey40CTtUi89w',
    appId: '1:561338680433:web:9139f6f5a4a0f6a33f07d0',
    messagingSenderId: '561338680433',
    projectId: 'mail-ceb33',
    authDomain: 'mail-ceb33.firebaseapp.com',
    storageBucket: 'mail-ceb33.appspot.com',
    measurementId: 'G-W0N9D64XQ0',
  );
}
